sklintyg/frontend

packages/webcert/src/feature/certificate/Certificate.tsx
Fixes strange rendering bug in Chromium (affects Chrome and Edge) where the sign button disappears after clicking it (setting active focus styles with outline) and subsequently scrolling up and clicking on a part of the document (must be the top part visible within one viewport unit). This is a known issue in Chromium which also concerns fixed or absolutely positioned elements (https://bugs.chromium.org/p/chromium/issues/detail?id=335442)
=> INTYGFV-14332: Fix disappearing sign button

packages/common/src/utils/certificateUtils.ts, packages/common/src/utils/validationUtils.ts, packages/webcert/src/feature/certificate/Certificate.tsx, packages/webcert/src/feature/certificate/Inputs/UeRadioGroupOptionalDropdown.tsx, packages/webcert/src/feature/certificate/Question/Question.tsx, packages/webcert/src/feature/certificate/Question/QuestionWithSubQuestions.test.tsx, packages/webcert/src/feature/certificate/Question/QuestionWithSubQuestions.tsx, packages/webcert/src/store/certificate/certificateSelectors.test.ts, packages/webcert/src/store/certificate/certificateSelectors.ts, packages/webcert/src/store/fmb/fmbReducer.ts
Business rules:
* Request for complements are only sent for main questions
* Notice on request for complements is shown after the main question and
sub questions if any
Note: the code still supports complements for sub questions, I saw no
need rewrite that logic.
=> INTYGFV-14421: Ensure complements are rendered after all sub questions

packages/webcert/src/components/certificateList/CertificateList.tsx, packages/webcert/src/components/commonLayout/CommonLayout.tsx, packages/webcert/src/components/patient/PatientSearch.tsx, packages/webcert/src/feature/list/List.tsx, packages/webcert/src/page/CertificatePage.tsx, packages/webcert/src/page/ListPage.tsx
Fixes inconsistencies for main contents padding/margin, some examples:
| search | create certificate|
|----|----|
| ![2022-07-21 09_03_22-Webcert](https://user-images.githubusercontent.com/28404/180152003-35910d3c-e7a0-43b2-a584-f0944362b3d1.png) | ![2022-07-21 09_08_47-Webcert](https://user-images.githubusercontent.com/28404/180152015-907c32ee-f692-46bc-b834-9d9ebc75d7dc.png) |
Fixed issues with not filling the page
And issues with going over the page limit
| create certificate | certificate page |
|----|----|
| ![2022-07-21 09_05_41-Webcert](https://user-images.githubusercontent.com/28404/180152393-cba7cd47-a184-41e5-99b9-0bc5fcf5a308.png) | ![2022-07-21 09_12_41-Webcert](https://user-images.githubusercontent.com/28404/180152796-dd4c00fc-f805-438c-ba82-7b2c94b5e57b.png) |
=> INTYGFV-14732: Fix margin, padding and layout issues

packages/webcert/src/page/ListPage.tsx
Apparently the effect needs to be triggered whenever hasUpdatedConfig is
updated regardless whether is has the same values as previous render or
not.
=> Bugfix: Infinite loading loop on list page view for unhandled issues

packages/webcert/src/feature/certificate/Question/QuestionUvResolve.tsx
Since UE_MESSAGE does not contain any values, we need to add this if-statement above the check:
``if (question.value == null || question.visible === false || question.style === CertificateDataElementStyleEnum.HIDDEN) {
return null
}``
=> INTYGFV-14488: Changed position of if-statement so that we are able to display UE_MESSAGES.

packages/webcert/src/feature/certificate/CertificateHeader/Status/AvailableForPatientStatus.test.tsx, packages/webcert/src/feature/certificate/CertificateHeader/Status/AvailableForPatientStatus.tsx
This is a quick fix checking if certificate type is db or doi, and then not displaying status
In the future, a more general solution could be supplying info on this in certificate metadata instead, like we do with the sent to status.
=> INTYGFV-15189: removed available to patient status for signed death and cause of death certificates

packages/common/src/components/Inputs/Dropdown.tsx
the dropdown component sometimes renders an error in the console log, due to null in the value parameter. 
I've added a null check, so an empty string is passed instead of null
=> added null check to value prop in dropdown

packages/webcert/src/page/CreatePage.tsx
I think the clraeing of patient on history.pop is legacy from when search and create was one page, and is not needed now
=> INTYGFV-14805: removed the clearing of patient on history.pop on create page, to ensure patient isn't cleared when back button is pressed

packages/webcert/src/components/error/modals/ErrorModalBase.tsx, packages/webcert/src/components/error/modals/SignCertificateError.tsx
The padding for error modal is set by the inera css and changing it would probably lead to some other text wrapping at inconvenient places, best left untouched. I made sure that each paragraph has proper spacing and the button should be centered.
=> INTYGFV-15421: Fix button alignment error message

yarn.lock
Changes to `yarn.lock` should always be included in PR when installing or updating dependencies.
=> Missing dependency in yarn.lock

apps/rehabstod/src/components/SickLeave/RekoStatusDropdown.tsx, apps/rehabstod/src/pages/CurrentSickLeaves/CurrentSickLeaves.tsx, apps/rehabstod/src/pages/CurrentSickLeaves/components/Filters.tsx, apps/rehabstod/src/pages/CurrentSickLeaves/components/ModifySicknessTableColumns.tsx, apps/rehabstod/src/pages/CurrentSickLeaves/components/TableBodyRows.tsx, apps/rehabstod/src/pages/CurrentSickLeaves/components/TableHeaderRow.tsx, apps/rehabstod/src/pages/LUCertificates/LUCertificates.tsx, apps/rehabstod/src/pages/LUCertificates/LUCertificatesFilters.tsx, apps/rehabstod/src/pages/Patient/Patient.tsx, apps/rehabstod/src/pages/Patient/components/PatientRekoStatus.tsx, apps/rehabstod/src/pages/Patient/components/patientLU/PatientLUCertificatesTable.tsx, apps/rehabstod/src/pages/Patient/components/patientSickLeaves/ModifyPatientTableColumns.tsx, apps/rehabstod/src/pages/Patient/components/patientSickLeaves/PatientSickLeaves.tsx, apps/rehabstod/src/store/api.ts, apps/rehabstod/src/store/hooks.ts
Instead of having unique tags per endpoint, we can have common tags that get invalidated for multiple endpoints. For example, if we have endpoints that need to be invalidated when the user settings get updated, we can simply tag them together with "User".
=> Simplify API by reducing tags

apps/minaintyg/package.json, apps/rehabstod/package.json, apps/webcert/package.json, package.json, packages/common/package.json, packages/components/package.json, packages/fake/package.json, packages/utils/package.json
https://github.com/sklintyg/frontend/pull/1153 caused strange issues, example: https://github.com/sklintyg/frontend/actions/runs/6557585241/job/17809465949
Reverting so that tests are executed for each package but keep changes for linting and formatting.
=> Fix lint-stage issue

apps/minaintyg/src/components/ProtectedRoute/ProtectedRoute.test.tsx, apps/minaintyg/src/components/ProtectedRoute/ProtectedRoute.tsx, apps/minaintyg/src/pages/Welcome/components/FakeLoginForm.tsx, apps/minaintyg/src/router.tsx, apps/minaintyg/src/store/testabilityApi.ts
* Should not render children while loading user in `ProtectedRoute`
* Redirect to `/welcome` when in development mode and not logged in
* Added button from `/welcome` to activate SAML login
* Navigate to `/intyg` when using fake-login
=> INTYGFV-16000: Login issues

apps/minaintyg/src/components/FilterAccordion/FilterAccordion.test.tsx, apps/minaintyg/src/components/FilterAccordion/FilterAccordion.tsx, apps/minaintyg/src/components/FilterAccordion/__snapshots__/FilterAccordion.test.tsx.snap, apps/minaintyg/src/components/Layout/ScrollTopButton.tsx, apps/minaintyg/src/components/PageDivider/PageDivider.test.tsx, apps/minaintyg/src/components/PageDivider/PageDivider.tsx, apps/minaintyg/src/components/PageHeading/PageHeading.tsx, apps/minaintyg/src/components/PageHeading/__snapshots__/PageHeading.test.tsx.snap, apps/minaintyg/src/index.css, apps/minaintyg/src/pages/Certificate/CertificatePage.tsx, apps/minaintyg/src/pages/Certificate/__snapshots__/CertificateListPage.test.tsx.snap, apps/minaintyg/src/pages/Certificate/__snapshots__/CertificatePage.test.tsx.snap, apps/minaintyg/src/pages/Certificate/__snapshots__/SendCertificatePage.test.tsx.snap, apps/minaintyg/src/pages/Certificate/components/CertificateCard/CertificateCardSummary.tsx, apps/minaintyg/src/pages/Certificate/components/CertificateCard/__snapshots__/CertificateCardSummary.test.tsx.snap, apps/minaintyg/src/pages/Certificate/components/CertificateInformation.tsx, apps/minaintyg/src/pages/Certificate/components/CertificateListFilter/CertificateListFilter.tsx, apps/minaintyg/src/pages/Certificate/components/CertificateListOrder/CertificateListOrderButton.tsx, apps/minaintyg/src/pages/Certificate/components/CertificateListOrder/__snapshots__/CertificateListOrder.test.tsx.snap, apps/minaintyg/src/pages/Certificate/components/EmptyCertificateListInfo.test.tsx, apps/minaintyg/src/pages/Certificate/components/EmptyCertificateListInfo.tsx, apps/minaintyg/src/pages/Certificate/components/SendCertificateActions/SendCertificateActions.tsx, apps/minaintyg/src/pages/Certificate/components/__snapshots__/CertificateInformation.test.tsx.snap, apps/minaintyg/src/pages/Certificate/components/__snapshots__/EmptyCertificateListInfo.test.tsx.snap
- Breadcrumbs should have IDS link styling
- `ScrollTopButton` should appear earlier.
- `PageDivider` should use a brighter color
- Convert `<strong>` to heading elements
- Update alert text when filter yield no result
- Filter options in 2x2 grid
- Filter text should contain "Visar"
- Move action buttons to the right
- Add `PageDivider` between actions and certificate on desktop
- Remove `PageDivider` between certificate information and content
- Add rounded corner for last header cell in `<tbody>`
- "Tillbaka till intyget" should be made primary when certificate is successfully sent
=> INTYGFV-16019 & INTYGFV-16021 & INTYGFV-16020: Design touchups

apps/minaintyg/src/index.css, apps/rehabstod/src/index.css
IDS has no fallbacks on the font families, in case of failed download or missing glyphs the applications can look broken.
For 1177, fonts are currently defined as:
```css
--font-family_1: "Open Sans";
--font-family_2: "Inter";
```
Fallbacks are from https://github.com/system-fonts/modern-font-stacks
=> Add fallbacks to fonts

apps/webcert/package.json, apps/webcert/src/components/fmb/FMBPanel.tsx, apps/webcert/src/feature/certificate/Certificate.tsx, apps/webcert/src/feature/certificate/CertificateSidePanel/CertificateSidePanel.tsx, apps/webcert/src/feature/certificate/Modals/DeathCertificateConfirmModalIntegrated.test.tsx, apps/webcert/src/feature/certificate/Modals/DeathCertificateConfirmModalIntegrated.tsx, apps/webcert/src/feature/certificate/Modals/LuaenaConfirmModalIntegrated.test.tsx, apps/webcert/src/feature/certificate/Modals/LuaenaConfirmModalIntegrated.tsx, apps/webcert/src/feature/certificate/Question/Question.tsx, apps/webcert/src/feature/certificate/Question/QuestionComplements.tsx, apps/webcert/src/feature/certificate/Question/QuestionHeading.tsx, apps/webcert/src/feature/certificate/Question/QuestionUeResolve.tsx, apps/webcert/src/feature/certificate/Question/QuestionWithSubQuestions.tsx, apps/webcert/src/page/CertificatePage.tsx, apps/webcert/src/store/certificate/certificateSelectors.ts, apps/webcert/src/store/fmb/fmbActions.ts, apps/webcert/src/store/fmb/fmbMiddleware.test.ts, apps/webcert/src/store/fmb/fmbMiddleware.ts, apps/webcert/src/store/icf/icfMiddleware.test.ts, apps/webcert/src/store/icf/icfMiddleware.ts, apps/webcert/src/store/icf/icfReducer.ts, apps/webcert/src/store/srs/srsMiddleware.tsx, apps/webcert/src/store/store.ts, apps/webcert/tsconfig.json, pnpm-lock.yaml
__Fixes__
* Component re-rendering caused by imprecise `useSelector`
- Certificate
- CertificatePage
- Question
- QuestionWithSubQuestion
- CertificateSidePanel
* Unnecessary state updated due to listening for `updateCertificate` redux action.
-------
To make sure that components are not re-render unnecessary, it helps to use `isEqual` or more precise selectors - for example:
```
const certificateId = useSelector((state) => state.ui.uiCertificate.certificate?.metadata.id)
```
instead of
```
const metadata = useSelector((state) => state.ui.uiCertificate.certificate?.metadata)
const certificateId = metadata.id
```
These updates can be identified using react DevTools extension for chrome.
`updateCertificate` action was previously only called when a certificate was initially loaded. This has …
=> INTYGFV-16405 & INTYGFV-16424: Only fetch ICF when needed

apps/webcert/README.md, apps/webcert/src/faker/certificate/fakeCertificateMetaData.ts
`apps/webcert/tests/certificate/questions.spec.ts` tests are failing since the change to `messageTypes`
=> Fix broken e2e test

apps/minaintyg/src/components/ProtectedRoute/ProtectedRoute.tsx, apps/minaintyg/src/components/error/ErrorBoundary.test.tsx, apps/minaintyg/src/pages/Certificate/CertificatePage.test.tsx, apps/minaintyg/src/pages/Error/ErrorPage.test.tsx, apps/minaintyg/src/store/middleware/error.middleware.ts, apps/minaintyg/src/store/slice/session.slice.ts
* Do not call `ping` once session is over.
* Do not log failed `ping` requests unless it contains an error.
* Replace deprecated `AnyAction`.
* Remove unnecessary `startSession` reducer.
=> INTYGFV-16701: Simplify ping and session handling

apps/maintenance/vite.config.ts, apps/minaintyg/vite.config.ts, apps/rehabstod/vite.config.ts, apps/webcert/vite.config.ts
After updating vite it won't accept `localtest.me` domains to access the services by default.
=> Allow custom hostname

apps/minaintyg/src/pages/Certificate/components/CertificateBody/CertificateBody.tsx, apps/minaintyg/src/pages/Certificate/components/CertificateBody/__snapshots__/CertificateBody.test.tsx.snap
Snapshot tests for `CertificatePage` sometimes fails because `IDSAccordion` adds lean when put inside a `IDSCard`. This mitigates that by adding lean property from the start.
=> Fix flaky test

apps/webcert/src/page/SelectUnitPage.tsx
`SelectUnitPage` has been using an action instead of a selector, this has always returned true since an action returns an object but not a user object. Since `user` is not being used here, it should be safe to remove.
=> Wrong selector function

.github/workflows/ci.yml, .github/workflows/playwright.yml
Potential fix for [https://github.com/sklintyg/frontend/security/code-scanning/6](https://github.com/sklintyg/frontend/security/code-scanning/6)
To fix the problem, explicitly restrict the `GITHUB_TOKEN` permissions for the job in question by adding a `permissions` key. Since the workflow appears to only require reading repository content (checking out code and running tests) and does not perform any actions that require write access (such as creating issues, posting pull request comments, etc.), setting `permissions: contents: read` at the job level is the minimal and appropriate fix. If the entire workflow needs restrictive permissions, it can also be placed at the root, but per the CodeQL highlight (job line) and to be as minimally invasive as possible, we'll add it under the …
=> Potential fix for code scanning alert no. 6: Workflow does not contain permissions

apps/webcert/src/feature/list/ListTable.tsx, apps/webcert/src/feature/list/listUtils.test.tsx, apps/webcert/src/feature/list/listUtils.tsx, apps/webcert/src/feature/list/pagination/ListPagination.tsx, apps/webcert/src/page/CreatePage.tsx, apps/webcert/src/page/SignedCertificatesPage.tsx, apps/webcert/src/store/list/listMiddleware.ts
The "empty list message" is displayed when all filters have default values and the search result is 0. When resetting the filters they return to default and if the performed search had a result of 0 the empty message would be shown. To solve this, I make sure that we do another search once filters are reset.
=> K1J-1366: Perform search after updating default filter values
