packages/mockserver/src/app.ts
packages/mockserver/src/bootstrap/bed26d3e-7112-4f08-98bf-01be40e26c80.json
packages/webcert/src/components/header/WebcertHeaderUser.tsx
packages/webcert/src/feature/certificate/Category.tsx
packages/webcert/src/feature/certificate/Certificate.tsx
packages/webcert/src/feature/certificate/CertificateHeader/CertificateHeader.tsx
packages/webcert/src/feature/certificate/Question.tsx
packages/webcert/src/feature/certificate/UeRadio.tsx
packages/webcert/src/feature/certificate/UeTextArea.tsx
packages/webcert/src/page/CertificatePage.tsx
packages/webcert/src/store/certificate/certificateActions.ts
packages/webcert/src/store/certificate/certificateMiddleware.ts
packages/webcert/src/store/certificate/certificateReducer.ts
packages/webcert/src/store/certificate/certificateSelectors.ts
packages/webcert/src/store/user/userActions.ts
packages/webcert/src/store/user/userReducer.ts

Also update import-statement to common where it imported @frontend/common/src instead of @frontend/common.

Added logic to revoke certificates.

---

packages/common/src/components/UvText/UvText.tsx
packages/common/src/types/certificate.ts
packages/mockserver/src/app.ts
packages/mockserver/src/bootstrap/bed26d3e-7112-4f08-98bf-01be40e26c80.json
packages/mockserver/src/bootstrap/fk7804.json
packages/webcert/src/feature/certificate/Certificate.tsx
packages/webcert/src/feature/certificate/Inputs/UeRadio.tsx
packages/webcert/src/feature/certificate/Inputs/UeTextArea.tsx
packages/webcert/src/feature/certificate/Question/Question.tsx
packages/webcert/src/store/certificate/certificateMiddleware.ts
packages/webcert/src/store/certificate/certificateReducer.ts
packages/webcert/src/store/certificate/certificateSelectors.ts

.. Also adjusted components to work with the new types

INTYGFV-13564: Created FK7804 JSON, updated AF00213 JSON, created new interfaces for certificate configs, values and validations

---

packages/webcert/package.json
packages/webcert/src/App.tsx
yarn.lock

Uses React Error Boundaries (https://reactjs.org/docs/error-boundaries.html) to "catch" unexpected runtime errors. In order to simplify the implementation, + stick to functional components, this PR introduces react-error-boundary (https://github.com/bvaughn/react-error-boundary) as a new dependency.

INTYGFV-14231: Handle unexpected javascript runtime errors with error boundaries.

---

packages/common/src/components/Inputs/Typeahead.tsx
packages/webcert/src/components/icf/IcfDropdown.test.tsx
packages/webcert/src/components/icf/IcfDropdown.tsx
packages/webcert/src/components/icf/IcfRow.tsx
packages/webcert/src/components/icf/Styles.tsx
packages/webcert/src/feature/certificate/Certificate.tsx
packages/webcert/src/feature/certificate/CertificateContext.tsx
packages/webcert/src/feature/certificate/Inputs/Test/UeIcf.test.tsx

- Ensure correct scroll positions when tabbing between dropdown elements
- Trap focus to icf dropdown container
- Close icf dropdown container on escape press

INTYGFV-14434: Fix scroll and accessibility issues

---

yarn.lock

...due to errors during build of css

Revert to previous version of inera-core-css

---

packages/webcert/src/feature/certificate/Buttons/ForwardCertificateButton.tsx
packages/webcert/src/feature/certificate/Buttons/Test/ForwardCertificateButton.test.tsx
packages/webcert/src/feature/certificate/CertificateFooter/CertificateFooter.tsx
packages/webcert/src/feature/list/List.tsx
packages/webcert/src/feature/list/ListItemContent.tsx
packages/webcert/src/feature/list/test/List.test.tsx
packages/webcert/src/page/ListPage.tsx
packages/webcert/src/store/certificate/certificateMiddleware.ts

- Specific text in email and modal when forwarding question
- Url in email points to environment from where forwarding was triggered
- Typos

INTYGFV-13881: Fix bugs related to forwarding certificates

---

packages/common/src/components/Inputs/DatePickerCustom/DatePickerCustom.stories.tsx
packages/common/src/components/Inputs/DatePickerCustom/DatePickerCustom.tsx
packages/common/src/components/Inputs/DatePickerCustom/Styles.tsx
packages/webcert/src/feature/certificate/Inputs/UeCheckboxDate.tsx
packages/webcert/src/feature/certificate/Inputs/UeSickLeavePeriod/DateRangePicker.test.tsx
packages/webcert/src/feature/certificate/Inputs/UeSickLeavePeriod/DateRangePicker.tsx
packages/webcert/src/feature/list/filter/DateRangeFilter.tsx
packages/webcert/src/feature/list/test/DateRangeFilter.test.tsx

Fixed minor issues in DatePickerCustom component and added storybook story as a bonus.

INTYGFV-14714: Make sure onChange gets called when date is empty string

---

.vscode/extensions.json
README.md

This adds recommendations for plugins when a developer opens the project using vscode.

Adding vscode plugin recommendation to workspace

---

packages/common/src/types/certificate.ts
packages/common/src/utils/validationUtils.test.ts
packages/common/src/utils/validationUtils.ts
packages/webcert/src/feature/certificate/Inputs/UeUncertainDate.tsx

Modified the onchange events in uncertain date so that the correct values are dispatched

modified onChange so correct values are dispatched

---

packages/common/src/components/UvText/UvText.test.tsx
packages/common/src/components/UvText/UvText.tsx
packages/webcert/src/components/welcome/WelcomeDeepIntegration.tsx

The visibility flag is set from backend to determine if the message should be showed or not.

INTYGFV-14928: Added functionality to display UE_MESSAGE on signed certificate

---

packages/webcert/src/feature/certificate/CertificateSidePanel/AboutCertificatePanel.tsx

added padding to last p element of content, in order to ensure any content covered by footer is empty

bug/INTYGFV-14957 - fixed content of about certificate may in some cases be covered by footer banner

---

README.md

Add some fun action badges to readme

---

packages/common/src/components/Inputs/Typeahead.tsx
packages/webcert/src/feature/certificate/Inputs/UeDiagnosis/UeDiagnosis.tsx

Also needed to make modigication in UeDiagnosis.tsx in order t reset cursor position on close of suggestion list

modified typeahead component to not reset cursor value on dispatch.

---

packages/common/src/components/UnifiedView/Badge.tsx
packages/common/src/components/UnifiedView/UvBoolean/UvBoolean.tsx
packages/common/src/components/UnifiedView/UvCode/UvCode.tsx
packages/common/src/components/UnifiedView/UvDate/UvDate.tsx
packages/common/src/components/UnifiedView/UvDateRange/UvDateRange.tsx
packages/common/src/components/UnifiedView/UvText/UvText.tsx
packages/common/src/components/UnifiedView/UvUncertainDate/UvUncertainDate.tsx
packages/webcert/src/feature/certificate/Question/QuestionUvResolve.tsx

Fixes issue with not being able to open FK7804 and AG7804, issue was in `UvDateRange` where `.reverse()` tries to modify immutable `config.list`.
Extra in this PR:
* UvText should print out "Ej angivet" for missing text value
* Cleanup

INTYGFV-15124: Fix unable to view signed certificate

---

packages/common/src/components/UnifiedView/UvMedicalInvestigationList/UvMedicalInvestigationList.tsx

INTYGFV-15174: Wrong headers in UvMedicalInvestigation

---

packages/webcert/src/App.tsx
packages/webcert/src/setupProxy.js
packages/webcert/src/utils/Logout.tsx

Inspired by how @mww-sopra-steria  implemented it in Angular
When running locally we'll get an error since CSRF is not implemented locally, as I understand?
But hopefully this should work in our other environments
Might be possible to some pure js-solution, but @mww-sopra-steria  mentioned this should be done as form submit, if I understnd correctly, not sure why though
Maybe the logout methods in redux needs some updating too?

INTYGFV-15264: changed logout method to post

---

packages/webcert/src/feature/list/ListPageSizeFilter.tsx
packages/webcert/src/feature/list/filter/ListFilterContainer.tsx

INTYGFV-14669: positioned page size filter to the right, just above table, next to caption

---

packages/common/src/components/utils/ArrowToggle.tsx
packages/webcert/src/components/header/WebcertHeaderUnit.tsx
packages/webcert/src/components/header/WebcertHeaderUser.tsx

Same behavior on both of these elements

INTYGFV-15286: Highlight the whole element when blundering

---

packages/common/src/components/Inputs/Dropdown.tsx
packages/webcert/src/components/header/WebcertHeaderUnit.tsx
packages/webcert/src/components/header/WebcertHeaderUser.tsx

Also added pointers to dropdowns

INTYGFV-15286: Only add outline if unit or portal exist

---

packages/common/src/components/Inputs/DatePickerCustom/DatePickerCustom.tsx
packages/common/src/components/Inputs/TextArea.tsx
packages/common/src/components/Inputs/TextInput.tsx
packages/webcert/src/index.css

This included som restructuring of DatePickerCustom to achieve a desired focus behaviour

INTYGFV-15311: changed focus of text inputs to be a border rather than shadow

---

packages/common/src/components/Inputs/Dropdown.tsx

Revert "INTYGFV-15413: Update value when the component goes from disabled…"

---

packages/webcert/src/feature/certificate/ResponsibleHospName.tsx

INTYGFV-15475: Fix icon size and margin issue

---

.github/workflows/frontend.yml
.pnpmfile.cjs
packages/webcert/package.json
packages/webcert/src/index.tsx
pnpm-lock.yaml

A bit of a hack to solve issue with `connected-react-router` and `react-router-dom` when using pnpm

INTYGFV-15698: Dependency issue in webcert

---

apps/rehabstod/src/components/SelectRekoStatus/SelectRekoStatus.test.tsx
apps/rehabstod/src/components/SelectRekoStatus/SelectRekoStatus.tsx
apps/rehabstod/src/components/SickLeave/RekoStatusDropdown.tsx
apps/rehabstod/src/pages/CurrentSickLeaves/components/TableBodyRows.tsx
apps/rehabstod/src/pages/CurrentSickLeaves/components/filter/SelectFilter.test.tsx
apps/rehabstod/src/pages/CurrentSickLeaves/components/filter/SelectFilter.tsx
apps/rehabstod/src/pages/Patient/Patient.tsx
apps/rehabstod/src/store/api.ts
apps/rehabstod/src/utils/getRekoStatusSickLeaveTimestamp.test.ts
apps/rehabstod/src/utils/getRekoStatusSickLeaveTimestamp.ts

I've asked requirements if REKO-status should also work if no current sick leaves but only previous. If that's the case I'll update the solution.

INTYGFV-15357: Set REKO-status in patient view

---

apps/rehabstod/src/pages/LUCertificates/LUCertificates.tsx
apps/rehabstod/src/pages/LUCertificates/LUCertificatesTableBody.tsx
apps/rehabstod/src/router.tsx

"Läkarutlåtande" should still be highlighted when navigating from there to patient.

Fix minor issue with navigation from LU to patient view

---

apps/rehabstod/src/components/Table/filter/SelectFilter.tsx

Remove missing label warning

---

apps/rehabstod/src/components/Popover/Popover.test.tsx
apps/rehabstod/src/components/Table/EmptyPatientTableMessage.test.tsx
apps/rehabstod/src/components/Table/TableInfoMessage.test.tsx
apps/rehabstod/src/mocks/handlers/handlers.ts
apps/rehabstod/src/pages/Home/components/OverviewStatistics.test.tsx
apps/rehabstod/src/pages/Patient/components/patientOverview/PatientOverview.test.tsx
apps/rehabstod/src/pages/Patient/components/patientSickLeaves/PatientTableBody.test.tsx
apps/rehabstod/src/pages/Welcome/Welcome.test.tsx
apps/rehabstod/src/setupTests.ts
apps/rehabstod/src/utils/fake/fakePatient.ts
apps/rehabstod/src/utils/fake/fakeSickLeave.ts
apps/rehabstod/src/utils/fake/fakeUser.ts
apps/rehabstod/src/utils/fake/fakeVardenhet.ts
apps/rehabstod/src/utils/fake/fakeVardgivare.ts
apps/rehabstod/src/utils/hasUserFeature.test.ts
apps/rehabstod/vite.config.ts
apps/webcert/vite.config.ts
packages/common/vite.config.ts
packages/eslint-config-custom/index.js
packages/fake/src/index.ts

* Add silent flag to vitest when running in CI (github actions)
* Fix issues with faker functions not producing unique results
* Fix issues with wrong parent element warnings in tests
* Remove faker seed from setupTest, making unique fake data the default

INTYGFV-15744: Further reduce test noise

---

apps/rehabstod/src/pages/Home/components/graph/TotalSickLeavesGraph.tsx

INTYGFV-15770: Graph focus border

---

apps/rehabstod/src/components/Form/Date/DateFieldSegment.tsx
apps/rehabstod/src/components/Form/Date/DatePicker/DatePicker.test.tsx
apps/rehabstod/src/components/Form/Date/DatePicker/DatePicker.tsx
apps/rehabstod/src/components/Form/Date/DateRangePicker/DateRangePicker.test.tsx
apps/rehabstod/src/components/Form/Date/DateRangePicker/DateRangePicker.tsx
apps/rehabstod/src/components/Form/Date/hooks/useDateFieldFocus.ts

* Added ability to clear fields with backspace
* Placeholder color should now be neutral-20
Adding a reset button proved to be challenging, leaving that out of the scope for now.

INTYGFV-15873: Handle date field focus on backspace

---

apps/minaintyg/index.html
apps/minaintyg/src/router.tsx

*  Emulate the browser's scroll restoration on location changes
https://reactrouter.com/en/main/components/scroll-restoration

Add scroll restoration

---

apps/minaintyg/src/pages/Certificate/CertificatePage.test.tsx
apps/minaintyg/src/pages/Certificate/SendCertificatePage.test.tsx
apps/minaintyg/src/pages/Certificate/__snapshots__/CertificatePage.test.tsx.snap
apps/minaintyg/src/pages/Certificate/__snapshots__/SendCertificatePage.test.tsx.snap
apps/minaintyg/src/pages/Certificate/components/CertificateCard/CertificateCardEvents/__snapshots__/CertificateCardEvents.test.tsx.snap
apps/minaintyg/src/pages/Certificate/components/CertificateEventsInfo/CertificateEventsInfo.tsx
apps/minaintyg/src/pages/Certificate/components/CertificateFooter.test.tsx
apps/minaintyg/src/pages/Certificate/components/CertificateFooter.tsx
apps/minaintyg/src/pages/Certificate/components/CertificateInformation.test.tsx
apps/minaintyg/src/pages/Certificate/components/__snapshots__/CertificateInformation.test.tsx.snap
apps/minaintyg/src/schema/certificate.schema.ts

* Remove `,` from footer
* Remove `:` from event list

INTYGFV-16042: Formatting issues

---

apps/minaintyg/src/components/Layout/Layout.tsx
apps/minaintyg/src/components/Layout/__snapshots__/Layout.test.tsx.snap
apps/minaintyg/src/pages/Certificate/CertificatePage.test.tsx
apps/minaintyg/src/pages/Certificate/CertificatePage.tsx
apps/minaintyg/src/pages/Certificate/SendCertificatePage.tsx
apps/minaintyg/src/pages/Certificate/__snapshots__/CertificatePage.test.tsx.snap
apps/minaintyg/src/pages/Certificate/__snapshots__/SendCertificatePage.test.tsx.snap
apps/minaintyg/src/pages/Certificate/components/CertificateFooter.test.tsx
apps/minaintyg/src/pages/Certificate/components/CertificateFooter.tsx
apps/minaintyg/src/pages/Certificate/components/CertificateInformation.test.tsx
apps/minaintyg/src/pages/Certificate/components/CertificateInformation.tsx
apps/minaintyg/src/pages/Certificate/components/SendCertificateActions/SendCertificateActions.test.tsx
apps/minaintyg/src/pages/Certificate/components/SendCertificateActions/SendCertificateActions.tsx
apps/minaintyg/src/pages/Certificate/components/__snapshots__/CertificateInformation.test.tsx.snap
apps/minaintyg/tailwind.config.ts

This partially fixes things for INTYGFV-16020 as well, due to shared components.

INTYGFV-16021: Update design for sending certificate

---

apps/rehabstod/src/components/Table/filter/SelectFilter.tsx
apps/rehabstod/src/pages/CurrentSickLeaves/components/CurrentSickLeavesFilters.tsx
apps/rehabstod/src/pages/CurrentSickLeaves/components/PrintTable.test.tsx
apps/rehabstod/src/pages/CurrentSickLeaves/components/PrintTable.tsx

* Italic text for sickleave that are ended (INTYGFV-16035)
* Personal information filter is now shown
* QAFilter is now shown
* Diagnostic should no longer overflow it's container

INTYGFV-16004 & INTYGFV-16035: Print issues

---

apps/minaintyg/src/components/Layout/Layout.tsx
apps/minaintyg/src/components/Layout/ScrollTopButton.tsx
apps/minaintyg/src/components/Layout/__snapshots__/Layout.test.tsx.snap
apps/minaintyg/src/pages/Certificate/components/CertificateActions/CustomizePrintDialog.tsx

* Fix issue with too large dialog for custom print
* Fixes issue with focus reset on mobile

INTYGFV-16153: Update dialog width and scroll to top focus reset

---

apps/minaintyg/src/components/Layout/Breadcrumbs.tsx

INTYGFV-16205: fix undefined matches

---

apps/rehabstod/src/pages/Patient/components/PatientAccordion/PatientAccordion.tsx
apps/rehabstod/src/pages/Patient/components/patientAG/PatientAGCertificatesTable.tsx
apps/rehabstod/src/pages/Patient/components/patientOverview/ExpandableCard.tsx
apps/rehabstod/src/pages/Patient/components/patientOverview/PatientOverviewCard.tsx
apps/rehabstod/src/pages/Patient/components/patientOverview/open/OpenInformationWithConsent.tsx
apps/rehabstod/src/pages/Patient/components/patientSickLeaves/PatientSickLeavesTable.tsx

This reverts commit 35930be2e6f33e4502666845e4f1780a19fb1d78.

Revert "INTYGFV-16038: Fixed heading levels for patient table (#1256)"

---

apps/webcert/src/feature/certificate/UnifiedEdit/UeCheckboxDateRangeList/UeCheckboxDateRangeList.test.tsx
apps/webcert/src/feature/certificate/UnifiedEdit/UeCheckboxDateRangeList/UeCheckboxDateRangeList.tsx
apps/webcert/src/types/certificate.ts

INTYGFV-16524: UeCheckboxDateRangeList should display label if present.

---

apps/webcert/src/store/welcome/welcomeMiddleware.ts

Issue https://github.com/vitejs/vite/issues/9520 has been resolved

Remove deprecated vite fix

---

apps/minaintyg/src/components/error/ErrorPageAction.test.tsx
apps/minaintyg/src/components/error/ErrorPageAction.tsx
apps/minaintyg/src/components/error/ErrorPageHero.tsx
apps/minaintyg/src/components/error/__snapshots__/ErrorPageAction.test.tsx.snap
apps/minaintyg/src/components/error/__snapshots__/ErrorPageHero.test.tsx.snap
apps/minaintyg/src/schema/error.schema.ts

Added underage error page and some readability improvements to components

INTYGFV-16596: Add underage error page

---

apps/webcert/src/components/Tabs/Tabs.tsx

K1J-285: Missing scroll for tab panel

---

apps/webcert/src/components/srs/minimizedView/SrsMinimizedView.tsx
apps/webcert/src/components/srs/panel/SrsPanel.test.tsx

Changed title in SRS panel for rehabkoordinering
From: Som rehabkoordinator, tänk på att
To: Vid koordinering, tänk på att

SRS-2024: Changed title in SRS panel for rehabkoordinering

---

apps/webcert/src/components/UnifiedView/UvDateRange/UvDateRange.test.tsx
apps/webcert/src/components/UnifiedView/UvDateRange/UvDateRange.tsx
apps/webcert/src/feature/certificate/UnifiedEdit/UeDateRange/UeDateRange.test.tsx
apps/webcert/src/feature/certificate/UnifiedEdit/UeDateRange/UeDateRange.tsx

K1J-969: Refactor UvDateRange component and corresponding tests

---

apps/webcert/src/faker/certificate/fakeCertificateData.ts
apps/webcert/src/store/icf/icfMiddleware.test.ts
apps/webcert/src/utils/validation/getDecoratedCertificateData.test.ts

General improvement taken from work done in #1456

Improved typescript for fakeCertificateDataElement
